services:
  - type: web
    name: iron-steel-business-api
    env: python
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET_KEY
        generateValue: true
    disk:
      name: sqlite-data
      mountPath: /opt/render/project/src/instance
      sizeGB: 1 